version: '3'
services:
  reverse_proxy_server:
    image: nginx:latest
    restart: always
    ports:
      - "80:3000"
    volumes:
      - ./fallback_server/static_files:/srv/www/static
      # - ../data/attachments:/srv/www/attachments
      - ./reverse_proxy_server/development.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      # - api_server
      - frontend_dev_server
      - fallback_server

  api_server:
    build: './api_server'
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./api_server:/src
      - /src/node_modules/
      # - ./frontend/src:/frontend/src
      # - ../data/attachments:/data/attachments
    environment:
      PORT: 3001
      NODE_ENV: development
      DATABASE_URI: mongodb://db:27017/maindb
      DOMAIN_NAME: http://127.0.0.1
    env_file:
      - ../config/env-vars.dev.env
    command: [ "yarn", "develop"]
    depends_on:
      - db

  fallback_server:
    build: './fallback_server'
    restart: always
    ports:
      - "3002:3002"
    volumes:
      - ./fallback_server:/src
      - ./frontend/src:/frontend/src
      - /src/node_modules/
    environment:
      PORT: 3002
      NODE_ENV: development
    command: [ "./node_modules/.bin/nodemon"]
    # depends_on:
      # - api_server

  frontend_dev_server:
    build: './frontend'
    volumes:
      - ./frontend:/src/
      - /src/node_modules/
      - ./api_server:/api_server/
    ports:
      - "3003:3003"
    environment:
      DEV_SERVER_PORT: 3003
      NODE_ENV: development
    command: [ "yarn", "webpack-dev-server" ]

  db:
    image: mongo
    restart: always
    volumes:
      - ./data/db/mongo:/data/db
    ports:
      - "27017:27017"
