export const actionType = {
  STATUS_ADD_OP: "STATUS_ADD_OP",
  STATUS_REMOVE_OP: "STATUS_REMOVE_OP",
  UPDATE_CATEGORIES: "UPDATE_CATEGORIES",
  UPDATE_SCENE_CATALOG: "UPDATE_SCENE_CATALOG",
  UPDATE_SCENE_CATALOG_FILTER: "UPDATE_SCENE_CATALOG_FILTER",
  UPDATE_SCENE_GLASSES: "UPDATE_SCENE_GLASSES",
  UPDATE_SCENE_LANDING: "UPDATE_SCENE_LANDING",
};
